// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDftkp_SHDrJqXmN7q-sjXRUQ5iJeXhKnA',
    appId: '1:649174638932:web:cbc0119969a9173f8ee8c1',
    messagingSenderId: '649174638932',
    projectId: 'udemy-1e36f',
    authDomain: 'udemy-1e36f.firebaseapp.com',
    databaseURL: 'https://udemy-1e36f-default-rtdb.firebaseio.com',
    storageBucket: 'udemy-1e36f.appspot.com',
    measurementId: 'G-3W7ZGP3YZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhGYhs1OpBwfBuuXvnqT6KVvGJraCb4Hk',
    appId: '1:649174638932:android:38c5731af74227878ee8c1',
    messagingSenderId: '649174638932',
    projectId: 'udemy-1e36f',
    databaseURL: 'https://udemy-1e36f-default-rtdb.firebaseio.com',
    storageBucket: 'udemy-1e36f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPfXzvC7JXms-Wnca1SFRqGD5aQZAQJQo',
    appId: '1:649174638932:ios:b30739379aae38be8ee8c1',
    messagingSenderId: '649174638932',
    projectId: 'udemy-1e36f',
    databaseURL: 'https://udemy-1e36f-default-rtdb.firebaseio.com',
    storageBucket: 'udemy-1e36f.appspot.com',
    iosBundleId: 'com.example.udemy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPfXzvC7JXms-Wnca1SFRqGD5aQZAQJQo',
    appId: '1:649174638932:ios:b30739379aae38be8ee8c1',
    messagingSenderId: '649174638932',
    projectId: 'udemy-1e36f',
    databaseURL: 'https://udemy-1e36f-default-rtdb.firebaseio.com',
    storageBucket: 'udemy-1e36f.appspot.com',
    iosBundleId: 'com.example.udemy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDftkp_SHDrJqXmN7q-sjXRUQ5iJeXhKnA',
    appId: '1:649174638932:web:bd9c751d745e9e708ee8c1',
    messagingSenderId: '649174638932',
    projectId: 'udemy-1e36f',
    authDomain: 'udemy-1e36f.firebaseapp.com',
    databaseURL: 'https://udemy-1e36f-default-rtdb.firebaseio.com',
    storageBucket: 'udemy-1e36f.appspot.com',
    measurementId: 'G-W627FGQVJD',
  );
}
